/*
SCOPO:

GLOBAL


LOCAL


- O ESCOPO DETERMINA A VISIBILIDADE DE UMA VARIAVÉL
- AS FUNÇÕES NO JS CRIAM O SEU PRÓPRIO ESCOPO
    - AS VARIÁVEIS DE UMA FUNÇÃO NÃO SÃO ACESSÍVEIS FORA DELA

*/




function teste(){
let a = 123
console.log(a)
}

teste()


/*
TODA VARIAÇÃO DECLARADA DENTRO DOS COCHETES VAI SER CONSIDERADA UM ESCOPO LOCAL

TODA VARIAÇÃO QUE FOR DECLARADA FORA DE QUALQUER FUNÇÃO ELA É CONSIDERADA GLOBAL
OBS: TOMAR CUIDADO COM O ESCOPO GLOBOAL ELE PODE OCASIONAR VÁRIOS BUGS NO SISTEMA E NA SUA PROGRAMAÇÃO NUM TODO. 
*/